auth:
    jwt:
        issuer: https://sample.com
        secretKey: secret
aws:
    s3:
        access:
            key:
                id: access_key
        bucket:
            name: bucket
        endpoint:
            url: https://s3.region.amazonaws.com
        secret:
            access:
                key: secret_key
spring:
    datasource:
        connection:
            timeout: 60000
        driver-class-name: com.mysql.cj.jdbc.Driver
        idle:
            timeout: 10000
        maximum:
            pool:
                size: 100
        minimum:
            idle: 50
        password: 123456
        url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true
