spring:
  application:
    name: configuration
  profiles:
    active: native
  cloud:
    config:
      server:
        # use cloud for storing configuration files
#        git:
#          uri: https://github.com/supertappo/backend-configuration.git
#          search-paths: startup-configs
#          username: username
#          password: password
#          clone-on-start: true
        # use local for storing configuration files
        native:
          search-locations:
          - /opt/supertappo/startup-configs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/
  instance:
    prefer-ip-address: true

info:
  component: Configuration Server

server:
  port: 8888
